old_litres_per_flush = 15
new_litres_per_flush = 2
cost_of_new_toilets = 150
toilets_per_person = 3
daily_number_of_flushes = 14
size_of_community = int(input())
cost_of_water_saved = size_of_community * cost_of_new_toilets;
toilets_are_used = (size_of_community // toilets_per_person)
if(size_of_community % 3 != 0):
    toilets_are_used += 1
old_water_flushed_per_day = (( toilets_are_used * daily_number_of_flushes) * old_litres_per_flush);
new_water_flushed_per_day = ((toilets_are_used * daily_number_of_flushes) * new_litres_per_flush);
litres_of_water_saved_per_day = old_water_flushed_per_day - new_water_flushed_per_day;
print("Old Water flushed per day => ", old_water_flushed_per_day)
print("New Water flushed per day => ", new_water_flushed_per_day)
print("Litres of Water saved per day => ", litres_of_water_saved_per_day)